version: 2
jobs:
  build:
    working_directory: ~/oauth2-example

    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:
      - checkout
      - restore_cache:
          key: oauth2-example-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: oauth2-example-{{ checksum "pom.xml" }}
      - run: mvn clean test