version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - run:
          name: Build application Docker image
          command: |
            docker-compose build
      - run:
          name: Log in to docker hub
          command: |
            docker login --username=frast --password=${DOCKER_HUB_TOKEN}
      - run:
          name: Tag docker images
          command: |
            docker images
      - run:
          name: Tag docker images
          command: |
            docker tag oauth2-example_oauth2-resource-server:latest frast/circleci-test
      - run:
          name: Push docker images
          command: |
            docker push frast/circleci-test