version: 2
jobs:
  build:
    working_directory: /oauth2-example
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            pip install \
              docker-compose==1.12.0
      - run:
          name: Build application Docker image
          command: |
            docker-compose build
      - run:
          name: Log in to docker hub
          command: |
            docker login --username=${DOCKER_HUB_USERNAME} --password=${DOCKER_HUB_TOKEN}
      - run:
          name: Show docker images
          command: |
            docker images
      - run:
          name: Tag docker images
          command: |
            docker tag oauth2example_oauth2-resource-server:latest frast/oauth2-example-resource-server
            docker tag oauth2example_oauth2-client:latest frast/oauth2-example-client
      - run:
          name: Push docker images
          command: |
            docker push frast/oauth2-example-resource-server
            docker push frast/oauth2-example-client